AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  todo-list-serverless

  SAM Template for todo-list-serverless

Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
  WebsiteCheckerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: website_checker/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        WebsiteChecker:
          Type: Api
          Properties:
            Path: /checker
            Method: get
  CreateTodoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create_todo/
      Handler: app.lambda_handler
      Runtime: python3.8

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  WebsiteCheckerApi:
    Description: "API Gateway endpoint URL for Prod stage for Website Checker function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/checker/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  WebsiteCheckerFunction:
    Description: "Website Checker Function ARN"
    Value: !GetAtt WebsiteCheckerFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
